description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine
machine:
  docker_layer_caching: <<parameters.use-docker-layer-caching>>
  image: <<parameters.image>>
parameters:
  image:
    default: 'ubuntu-2004:202107-02'
    type: string
  resource-class:
    default: medium
    type: string
  use-docker-layer-caching:
    default: false
    type: boolean
resource_class: <<parameters.resource-class>>
